# {player}为玩家名，{value}为幸运值
message:
  at_100: <§d算命占卜§r> 精灵们今天非常开心！他们会尽可能给所有人带来好运的。
  at_99: <§d算命占卜§r> 精灵们今天非常开心！他们会尽可能给所有人带来好运的。
  lt_90: <§d算命占卜§r> 精灵们今天的心情很不错。你今天要走运了。
  lt_60: <§d算命占卜§r> 精灵们今天的心情很不错。你今天要走运了。
  lt_50: <§d算命占卜§r> 精灵们今天没有任何感情倾向。因此今天的运势全掌握在你手中。
  at_50: <§d算命占卜§r> 这可罕见了。精灵们今天很冷漠。
  lt_40: <§d算命占卜§r> 今天精灵们有些烦躁。你要走霉运了。
  lt_11: <§d算命占卜§r> 今天精灵们十分气恼。你要走霉运了。
  lt_1: <§d算命占卜§r> 精灵今天十分不满。它们会竭尽全力给你捣蛋的。
  at_1: <§d算命占卜§r> 精灵今天十分不满。它们会竭尽全力给你捣蛋的。

  # at_100: '{player}今日气运是{value}！'
  # at_99: '{player}今日气运是{value}！'
  # lt_90: '{player}今日气运是{value}！'
  # lt_60: '{player}今日气运是{value}！'
  # lt_50: '{player}今日气运是{value}！'
  # at_50: '{player}今日气运是{value}！'
  # lt_40: '{player}今日气运是{value}！'
  # lt_11: '{player}今日气运是{value}！'
  # lt_1: '{player}今日气运是{value}！'
  # at_1: '{player}今日气运是{value}！'

# 今日人品的随机种子
secret: hello

# 玩家不在线时的消息
notOnline: §c玩家不在线
# 未指定玩家时的消息
needPlayer: §c未指定玩家
# 没有权限时的消息
noPermission: §c你没有权限
